from dataclasses import dataclass, field
from typing import Any


@dataclass
class EvaluationResult:
    """Result of evaluating a single scenario's output.

    Attributes:
        scenario_name: Name of the scenario that was evaluated.
        passed: ``True`` when all checks (contains + drift) passed.
        contains_score: Fraction of expected terms found (0.0–1.0).
        metrics: Detailed per-check metrics including ``drift_score``,
            ``found_terms``, ``missing_terms``, ``output_length``, and
            ``prompt_hash``.
        raw_output: The raw text generated by the backend.
        errors: Human-readable descriptions of any failed checks.
    """

    scenario_name: str
    passed: bool
    contains_score: float
    metrics: dict[str, Any] = field(default_factory=dict)
    raw_output: str = ""
    errors: list[str] = field(default_factory=list)


class Evaluator:
    """
    Checks model output against scenario expectations.

    Checks:
      - expected_contains: all listed strings must appear in output
      - drift: Jaccard similarity vs baseline output (when baseline provided)
    """

    def __init__(self, tolerance: float = 1.0):
        self.tolerance = tolerance  # minimum pass threshold

    def evaluate(
        self,
        scenario: "Scenario",
        output: str,
        previous_baseline: dict | None = None,
    ) -> EvaluationResult:
        """Evaluate *output* against *scenario* expectations.

        Args:
            scenario: The scenario whose ``expected_contains`` terms define
                the acceptance criteria.
            output: Raw text generated by the backend.
            previous_baseline: Optional dict from a saved baseline (must
                include a ``"raw_output"`` key) for drift detection.

        Returns:
            An :class:`EvaluationResult` with ``passed=True`` only when every
            expected term is present **and** the drift score (when a baseline
            is provided) is at or above ``self.tolerance``.
        """
        errors = []

        # ── contains check ────────────────────────────────────
        found, missing = [], []
        for term in scenario.expected_contains:
            (found if term.lower() in output.lower() else missing).append(term)

        n = len(scenario.expected_contains)
        contains_score = len(found) / n if n > 0 else 1.0
        if missing:
            errors.append(f"Missing expected terms: {missing}")

        # ── drift check ───────────────────────────────────────
        drift_score = None
        if previous_baseline and "raw_output" in previous_baseline:
            drift_score = self._jaccard(previous_baseline["raw_output"], output)
            if drift_score < self.tolerance:
                errors.append(
                    f"Drift detected: similarity {drift_score:.2f} < {self.tolerance:.2f}"
                )

        passed = not errors and contains_score >= self.tolerance

        return EvaluationResult(
            scenario_name=scenario.name,
            passed=passed,
            contains_score=contains_score,
            metrics={
                "found_terms": found,
                "missing_terms": missing,
                "drift_score": drift_score,
                "output_length": len(output),
                "prompt_hash": scenario.prompt_hash,
            },
            raw_output=output,
            errors=errors,
        )

    @staticmethod
    def _jaccard(a: str, b: str) -> float:
        w1, w2 = set(a.lower().split()), set(b.lower().split())
        if not w1 or not w2:
            return 0.0
        return len(w1 & w2) / len(w1 | w2)
